### ISSUE TITLE
An unhandled exception has been thrown: Error: Call to a member function getUID() on null nextcloud/apps/workflow_script/lib/Operation.php:318

### ISSUE THREAD

**Issue by BlablaBloblo** [nextcloud/workflow_script#108]
## Steps to reproduce
1. Enabled external storage for group -> no owner for some items

### Expected behaviour
No Crash ;)

### Actual behaviour
while regular nextcloud cron:

An unhandled exception has been thrown:
Error: Call to a member function getUID() on null in /home/www-data/nextcloud/apps/workflow_script/lib/Operation.php:318
Stack trace:
#0 /home/www-data/nextcloud/apps/workflow_script/lib/Operation.php(203): OCA\WorkflowScript\Operation->replacePlaceholderN()
.........

Suggested solution:

replace:

if (strpos($node->getPath(), $owner->getUID()) !== 0) {

by: 

if ($owner && (strpos($node->getPath(), $owner->getUID()) !== 0)) {

**Comment by joshtrichards** [comment]
Hi @BlablaBloblo:

Thanks for the report!

You didn't specify the versions of this app and groupfolders/etc, but this should have been addressed (mostly) by nextcloud/groupfolders#797 (I think).

We could maybe add some deeper error handling up a bit higher:

https://github.com/nextcloud/workflow_script/blob/4eb5897b4de5f392fba8309546c242316ad4bec4/lib/Operation.php#L252

But the real issue is that `$node->getOwner()` should never have a situation where it can end up being null (regardless of in-use Storage or Groups).

Can you still reproduce this behavior today on any supported release?

**Comment by BlablaBloblo** [comment]
Sorry, I changed the link to the external storage to work around the issue and cannot remember how it was before - it's 3 years ago at last. Thank you very much for coming back to this issue!
