### ISSUE TITLE
%n parameter is broken on GROUP FOLDERS

### ISSUE THREAD

**Issue by lbdroid** [nextcloud/workflow_script#113]
## Steps to reproduce
I'm attempting to make a simple script to use imagemagick's "convert" command to create a converted version of the file when a tag is assigned.

The script I'm running as a test is ```convert %f /var/www/nextcloud/data/%n.pdf```
Nextcloud's root is at the path ```/var/www/nextcloud/```

When cron.php calls the script, I get the following error;
```convert: unable to open image '/var/www/nextcloud/data/__groupfolders/1/[BAD STUFF]/path/to/file.jpg.pdf': No such file or directory @ error/blob.c/OpenBlob/2881.```

Where [BAD STUFF] is ```{username}/files/{groupfoldername}```

### Expected behaviour
That [BAD STUFF] should not be part of the %n parameter. Without it, the path would be correct and the script would work.

**Workflow Script app version:** 1.8.0

## Server configuration

**Operating system**: Rocky 8

**Web server:** Apache

**Database:** Maria

**PHP version:** 7.4

**Nextcloud Version:** 23

**Comment by lbdroid** [comment]
Added this kludge to buildCommand to make it work;

```
                        $ncRelPath = explode("/", $ncRelPath);
                        unset($ncRelPath[2]);
                        unset($ncRelPath[3]);
                        unset($ncRelPath[4]);
                        $ncRelPath = implode("/", $ncRelPath);

```

**Comment by blizzz** [comment]
It actually works as documented:

![Screenshot_20230606_132229](https://github.com/nextcloud/workflow_script/assets/2184312/69a88f46-02cb-4ae0-a446-4a5ca074bd52)

**Comment by Nils160988** [comment]
I am having the same issue and would ask @blizzz to reopen this ticket. It seems to be related to https://github.com/nextcloud/workflow_script/pull/64, but for groupfolders instead of shared folders.

For me, it yields
%n = __groupfolders/[id_of_groupfolder]/[username]/files/[name_of_groupfolder]/[path_to_file_within_groupfolder]
but it should be (as documented)
%n = __groupfolders/[id_of_groupfolder]/[path_to_file_within_groupfolder]

So, the middle part ([username]/files/[name_of_groupfolder]/), which forms the "base path" for regular files, needs to be removed in case of groupfolders.
