### ISSUE TITLE
ffmpeg throwing "Invalid data found when processing input"

### ISSUE THREAD

**Issue by i-oliva** [nextcloud/workflow_script#144]
## Steps to reproduce
1. Feed a file into ffmpeg e.g. `ffmpeg -i %f -vcodec libx264 -crf 20 %n_compressed.mp4`.
2. Upload a file
3. Error throws and can be seen inside /settings/admin/logging

```

Movie preview generation failed Output: ["ffmpeg version 5.0.1 Copyright (c) 2000-2022 the FFmpeg developers"," built with gcc 11.2.1 (Alpine 11.2.1_git20220219) 20220219"," configuration: --prefix=/usr --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libpulse --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-lto --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-librist --enable-libsrt --enable-libssh --enable-libvidstab --disable-stripping --disable-static --disable-librtmp --enable-libaom --enable-libopus --enable-libsoxr --enable-libwebp --enable-vaapi --enable-vdpau --enable-vulkan --enable-libdrm --disable-debug"," libavutil 57. 17.100 / 57. 17.100"," libavcodec 59. 18.100 / 59. 18.100"," libavformat 59. 16.100 / 59. 16.100"," libavdevice 59. 4.100 / 59. 4.100"," libavfilter 8. 24.100 / 8. 24.100"," libswscale 6. 4.100 / 6. 4.100"," libswresample 4. 3.100 / 4. 3.100"," libpostproc 56. 3.100 / 56. 3.100","/mnt/ncdata/tmp/oc_tmp_ANOfcg: Invalid data found when processing input"]

```

### Expected behaviour
When feeding a file to ffmpeg, it should not throw an error. 

Using nextcloud AIO 25

Apologies if I'm using the wrong placeholder format, perhaps you could suggest a correct one. Thanks in advance.

**Comment by blizzz** [comment]
Why should it not throw an error on invalid data?

**Comment by joshtrichards** [comment]
Hi @i-oliva:

Nextcloud/a Nextcloud app simply logging the errors it's provided isn't a bug. It's expected behavior.

If you don't want to see the error output from a script/command you execute, you can redirect it in the usual UNIX fashion. You'll have to decide whether that's a good idea or not for your use case... it's entirely up to you.


P.S. What types of files are your rules set up to send off to `ffmpeg`? Make sure you aren't sending non-audio/non-video files to `ffmpeg`. :-)

**Comment by AndyXheli** [comment]
Hey @joshtrichards just a thought is there a way to change the error level from error to warning on the nextcloud side since it's not really that hight properly or maybe make it informational ? Since it's really not a bug and the error really dose not come from nextcloud I would say make it more unde thr Info Level and if someone dose want to view it they can select the info level and it keeps the nextcloud logs more clean for important errors and warnings what do you think ?
